"""empty message

Revision ID: dbae508c8991
Revises: da5d7d673fa5
Create Date: 2025-07-23 22:49:22.457195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbae508c8991'
down_revision = 'da5d7d673fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.String(length=20), nullable=False))
        batch_op.drop_column('imdb_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
